### ISSUE TITLE
'no table section' error when compiling with 'lto = true' when using closures

### ISSUE THREAD

**Issue by nstoddard** [rustwasm/wasm-bindgen#1130]
If I enable `lto = true` in release mode, and the code uses closures, `wasm-bindgen` crashes with the error `'no table section'`. Code without closures works fine. It happens with either stable or nightly Rust; I'm using `wasm-bindgen 0.2.29`.

This can be reproduced by enabling LTO for the wasm-bindgen examples; the `closures` example crashes, but most other examples work fine. The minimal code below also has this issue:

``` rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen(start)]
pub fn main() {
    let closure = Closure::wrap(Box::new(move || {}) as Box<dyn FnMut()>);
}
```

```
+ cargo +nightly build --release --target wasm32-unknown-unknown
    Finished release [optimized] target(s) in 0.01s
+ wasm-bindgen target/wasm32-unknown-unknown/release/test.wasm --out-dir .
thread 'main' panicked at 'no table section', libcore/option.rs:1008:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:476
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::option::expect_failed
             at libcore/option.rs:1008
   9: wasm_bindgen_gc::LiveContext::add_table
  10: wasm_bindgen_gc::run
  11: wasm_bindgen_cli_support::js::Context::finalize
  12: wasm_bindgen_cli_support::Bindgen::_generate
  13: wasm_bindgen::main
  14: std::rt::lang_start::{{closure}}
  15: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  16: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  17: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  18: main
  19: __libc_start_main
  20: _start
```

**Comment by alexcrichton** [comment]
Thanks for the report! I can reproduce this and I'll try to dig into what's going on soon, definitely sounds like a wasm-bindgen bug!

**Comment by alexcrichton** [comment]
Should be fixed in https://github.com/rustwasm/wasm-bindgen/pull/1145!
