### ISSUE TITLE
Panic at 'index out of bounds: the len is 0 but the index is 0' on HEAD

### ISSUE THREAD

**Issue by rhysd** [rustwasm/wasm-bindgen#1222]
I confirmed
- this occurs at 92072bf03ccef297b3af2006e2a065eeea0254d5
- this does not occur at f8dabfca

## Repro

I'm sorry that I was not able to take enough time to create a minimal project for this issue, but I'm seeing this issue on my project.

Sequence to reproduce is as follows:

```
git clone https://github.com/rustwasm/wasm-bindgen.git
git clone https://github.com/rhysd/world-map-gen.git
cd wasm-bind-gen/crates/cli
cargo build
cd ../../../world-map-gen
cargo build --target wasm32-unknown-unknown
mkdir pkg
../wasm-bind-gen/target/debug/warm-bindgen target/wasm32-unknown-unknown/debug/world_map_gen.wasm --out-dir pkg
```

## Expected

Generates files in the `pkg` directory

## Actual

Panics as follows:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/cli-support/src/descriptor.rs:292:15
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Running with enabling backtrace shows a backtrace as follows:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/cli-support/src/descriptor.rs:292:15
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:325
   7: core::char::methods::<impl char>::escape_debug
             at src/libcore/panicking.rs:95
   8: core::char::methods::<impl char>::escape_debug
             at src/libcore/panicking.rs:71
   9: wasm_bindgen_cli_support::descriptor::get
             at crates/cli-support/src/descriptor.rs:292
  10: wasm_bindgen_cli_support::descriptor::Descriptor::_decode
             at crates/cli-support/src/descriptor.rs:131
  11: wasm_bindgen_cli_support::descriptor::Descriptor::decode
             at crates/cli-support/src/descriptor.rs:104
  12: wasm_bindgen_cli_support::js::Context::describe
             at crates/cli-support/src/js/mod.rs:1789
  13: wasm_bindgen_cli_support::js::SubContext::generate_struct
             at crates/cli-support/src/js/mod.rs:2588
  14: wasm_bindgen_cli_support::js::SubContext::generate
             at crates/cli-support/src/js/mod.rs:2309
  15: alloc::raw_vec::alloc_guard
             at crates/cli-support/src/lib.rs:220
  16: wasm_bindgen_cli_support::Bindgen::generate
             at /Users/rhysd/Develop/github.com/rustwasm/wasm-bindgen/crates/cli-support/src/lib.rs:150
  17: wasm_bindgen::rmain
             at crates/cli/src/bin/wasm-bindgen.rs:115
  18: wasm_bindgen::main
             at crates/cli/src/bin/wasm-bindgen.rs:74
  19: std::rt::lang_start::{{closure}}
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  20: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  21: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:102
  22: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  23: std::rt::lang_start
             at /rustc/9fda7c2237db910e41d6a712e9a2139b352e558b/src/libstd/rt.rs:74
  24: wasm_bindgen::rmain
```

**Comment by alexcrichton** [comment]
Thanks for the report! It looks like you're matching up a git version of the wasm-bindgen CLI though with a published version of the crate on crates.io? If that's the case then that may be where this error comes from. If you use `wasm-pack` and/or the published version of `wasm-bindgen-cli` on crates.io does it work for you?

**Comment by alexcrichton** [comment]
Ah ok, in that case I think this is expected where published versions are expected to be used against published versions on crates.io (note that `wasm-pack` does this for you automatically). We don't do a great job of "poisoning" git right now where git is considered incompatible with crates.io, but we should probably do that!

If this ends up being the bug here I'll open up a follow-up issue

**Comment by rhysd** [comment]
Thank you! I'll track the issue.
