### ISSUE TITLE
Webpack unable to parse wasm files since 0.2.35

### ISSUE THREAD

**Issue by stevebob** [rustwasm/wasm-bindgen#1246]
Running webpack on the [basic example in the guide](https://rustwasm.github.io/wasm-bindgen/whirlwind-tour/basic-usage.html) works fine with version 0.2.34 of wasm-bindgen* crates and wasm-bindgen-cli, but upgrading everything to 0.2.35 and 0.2.36 results in the following error:

```
$ npx webpack
Failed to decode custom "name" section @23898; ignoring (integer representation too long).
Hash: e49b6c9b2386a2dc300c
Version: webpack 4.29.3
Time: 624ms
Built at: 02/12/2019 11:25:06 PM
     Asset       Size  Chunks             Chunk Names
0.index.js   27.8 KiB       0  [emitted]  
1.index.js   3.67 KiB       1  [emitted]  
index.html  195 bytes          [emitted]  
  index.js   10.4 KiB    main  [emitted]  main
Entrypoint main = index.js
[./index.js] 82 bytes {main} [built]
[./js_hello_world.js] 1.47 KiB {1} [built]
[./js_hello_world_bg.wasm] 1.8 KiB {1} [built] [failed] [1 error]
    + 4 hidden modules
ERROR in ./js_hello_world_bg.wasm
Module parse failed: Unexpected section: 0xfa
You may need an appropriate loader to handle this file type.
Error: Unexpected section: 0xfa
    at CompileError.Error (native)
    at new CompileError (/home/travis/build/stevebob/js-hello-world/node_modules/@webassemblyjs/helper-api-error/lib/index.js:40:109)
    at parseSection (/home/travis/build/stevebob/js-hello-world/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1542:11)
    at Object.decode (/home/travis/build/stevebob/js-hello-world/node_modules/@webassemblyjs/wasm-parser/lib/decoder.js:1559:25)
    at decode (/home/travis/build/stevebob/js-hello-world/node_modules/@webassemblyjs/wasm-parser/lib/index.js:240:21)
    at WebAssemblyParser.parse (/home/travis/build/stevebob/js-hello-world/node_modules/webpack/lib/wasm/WebAssemblyParser.js:74:19)
    at doBuild.e (/home/travis/build/stevebob/js-hello-world/node_modules/webpack/lib/NormalModule.js:460:32)
    at runLoaders (/home/travis/build/stevebob/js-hello-world/node_modules/webpack/lib/NormalModule.js:342:12)
    at /home/travis/build/stevebob/js-hello-world/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/travis/build/stevebob/js-hello-world/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/travis/build/stevebob/js-hello-world/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/travis/build/stevebob/js-hello-world/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
    at provider (/home/travis/build/stevebob/js-hello-world/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9)
    at /home/travis/build/stevebob/js-hello-world/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:447:3)
 @ ./js_hello_world.js 2:0-44 10:71-82 11:45-56 34:16-38 47:15-25 50:8-28
 @ ./index.js
ERROR in chunk 1
f0aae4cdc94990e0c1c0.module.wasm
/home/travis/build/stevebob/js-hello-world/js_hello_world_bg.wasm
unexpected end
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
        + 2 hidden modules
The command "npx webpack" exited with 2.

```
I made a repo to demonstrate the problem. There is a branch for 0.2.34, 0.2.35, and 0.2.36:
https://travis-ci.org/stevebob/js-hello-world/branches

**Comment by alexcrichton** [comment]
Thanks for the report! I think that's the same [as this](https://github.com/rustwasm/wasm-bindgen/pull/1245#issuecomment-462940737) and @xtuc is investigating.

**Comment by greenpdx** [comment]
Update everything to the latest version is what I am reading. I will do that and report back.

**Comment by andrewdavidmackenzie** [comment]
I think I still see this issue in 0.2.45, would that be a surprise to folks?
