### ISSUE TITLE
panic with missing field structs

### ISSUE THREAD

**Issue by yanns** [rustwasm/wasm-bindgen#143]
I'm following this guide: https://rust-lang-nursery.github.io/rust-wasm/game-of-life/setup.html
```
$ cargo +nightly install wasm-bindgen-cli --version 0.2.1
```
This seems to install the 0.2.3 version instead of the 0.2.1, but it's maybe expected.
```
$ wasm-bindgen -V
wasm-bindgen 0.2.3
```

When trying to use it, I have the following error:
```
wasm-bindgen target/wasm32-unknown-unknown/debug/wasm_game_of_life.wasm --out-dir .
thread 'main' panicked at 'failed to decode what looked like wasm-bindgen data: missing field `structs` at line 1 column 355', /Users/yannsimon/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.3/src/lib.rs:223:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: <alloc::vec::Vec<T>>::retain
   7: wasm_bindgen_cli_support::Bindgen::_generate
   8: wasm_bindgen::main
   9: std::rt::lang_start::{{closure}}
  10: std::panicking::try::do_call
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start_internal
  13: main
```
(I'm on mac)

**Comment by alexcrichton** [comment]
Thanks for the report! I think we need to update the guide to go ahead and install the latest version, as I believe that's the issue here. Sorry about that! If you drop the `--version 0.2.1` flag you should be good to go.

**Comment by yanns** [comment]
Thanks for the quick report.

Installing the last version still produce the same error:
```
$ cargo +nightly uninstall wasm-bindgen-cli
$ cargo +nightly install wasm-bindgen-cli
$ wasm-bindgen -V
wasm-bindgen 0.2.4
$ wasm-bindgen target/wasm32-unknown-unknown/debug/wasm_game_of_life.wasm --out-dir .
thread 'main' panicked at 'failed to decode what looked like wasm-bindgen data: missing field `structs` at line 1 column 355', /Users/yannsimon/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.4/src/lib.rs:223:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic_fmt
   6: <alloc::vec::Vec<T>>::retain
   7: wasm_bindgen_cli_support::Bindgen::_generate
   8: wasm_bindgen::main
   9: std::rt::lang_start::{{closure}}
  10: std::panicking::try::do_call
  11: __rust_maybe_catch_panic
  12: std::rt::lang_start_internal
  13: main
```

**Comment by alexcrichton** [comment]
Hm oh dear! If you run `cargo update` does it help?

**Comment by yanns** [comment]
```
$ cargo update
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Removing fnv v1.0.6
    Updating serde v1.0.37 -> v1.0.39
    Updating serde_derive v1.0.37 -> v1.0.39
    Updating serde_derive_internals v0.23.0 -> v0.23.1
    Updating serde_json v1.0.13 -> v1.0.15
    Updating wasm-bindgen v0.2.1 -> v0.2.4
    Updating wasm-bindgen-backend v0.2.1 -> v0.2.4
    Updating wasm-bindgen-macro v0.2.1 -> v0.2.4
    Updating wasm-bindgen-shared v0.2.1 -> v0.2.4

$ cargo +nightly build --target wasm32-unknown-unknown && wasm-bindgen target/wasm32-unknown-unknown/debug/wasm_game_of_life.wasm --out-dir .
```
works!
Thanks a lot!
