### ISSUE TITLE
Build conflict with cssparser crate: proc_macro::__internal::with_sess() called before set_parse_sess()

### ISSUE THREAD

**Issue by jryans** [rustwasm/wasm-bindgen#160]
I would like to use `wasm-bindgen` together with the `cssparser` crate. However, at the moment, it seems to cause some kind of build conflict.

Let's start by creating an empty project:

```
$ cd lexer-test
$ cargo init --lib
$ cargo add css-parser wasm-bindgen
```

which leaves me with a `Cargo.toml` like so:

```
[package]
name = "lexer-test"
version = "0.1.0"
authors = ["J. Ryan Stinnett <jryans@gmail.com>"]

[dependencies]
wasm-bindgen = "0.2.5"
cssparser = "0.23.5"
```

Trying to build this empty project gives an error:
```
$ cargo build
RUST_BACKTRACE=1 cargo build
   Compiling cssparser v0.23.5
   Compiling wasm-bindgen-shared v0.2.5
error: failed to run custom build command for `cssparser v0.23.5`
process didn't exit successfully: `/Users/jryans/Projects/lexer-test/target/debug/build/cssparser-13a5f57b71b5e798/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-cfg=rustc_has_pr45225

--- stderr
thread 'main' panicked at 'proc_macro::__internal::with_sess() called before set_parse_sess()!', libproc_macro/lib.rs:1319:9
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: proc_macro::__internal::with_sess
   7: <proc_macro::TokenStream as core::str::FromStr>::from_str
   8: <syntax::parse::token::DelimToken as core::clone::Clone>::clone
             at /Users/travis/build/rust-lang/rust/src/libcore/str/mod.rs:2550
   9: core::clone::impls::<impl core::clone::Clone for bool>::clone
             at /Users/travis/build/rust-lang/rust/src/liballoc/str.rs:1814
  10: proc_macro2::imp::LexError
             at /Users/jryans/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.7/src/unstable.rs:30
  11: <syntax::parse::token::DelimToken as core::clone::Clone>::clone
             at /Users/travis/build/rust-lang/rust/src/libcore/str/mod.rs:2550
  12: core::clone::impls::<impl core::clone::Clone for bool>::clone
             at /Users/travis/build/rust-lang/rust/src/liballoc/str.rs:1814
  13: core::ptr::swap_nonoverlapping_bytes
             at /Users/jryans/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-0.3.7/src/lib.rs:85
  14: <proc_macro2::TokenStream as core::clone::Clone>::clone
             at /Users/travis/build/rust-lang/rust/src/libcore/str/mod.rs:2550
  15: <alloc::alloc::Global as core::alloc::Alloc>::realloc
             at /Users/travis/build/rust-lang/rust/src/liballoc/str.rs:1814
  16: syn::parse2::{{closure}}
             at /Users/jryans/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-0.13.1/src/lib.rs:640
  17: syn::parse2::{{closure}}
             at /Users/jryans/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-0.13.1/src/lib.rs:705
  18: build_script_build::match_byte::expand
             at ./build/match_byte.rs:20
  19: build_script_build::codegen::main
             at ./build.rs:32
  20: build_script_build::main
             at ./build.rs:46
  21: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  22: std::panicking::try::do_call
  23: __rust_maybe_catch_panic
  24: std::rt::lang_start_internal
  25: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  26: build_script_build::main
```

If I remove `wasm-bindgen`, the project builds successfully. It's not clear to me which of the two crates is causing trouble here.

### System info
macOS 10.13.4
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
Rust installed by rustup

**Comment by jryans** [comment]
Aha, thanks for those details!

Is there something different that `wasm-bindgen` could do instead to preserve span info while also allowing build scripts with `proc-macro2` from other crates like this? (I don't know very much about procedural macros in Rust yet, so apologies for the possible naive question!)

As a workaround though, it does sound nice to have some mechanism to disable the `nightly` feature here. Would that be a feature on this crate like `disable_spans` or something?

**Comment by jryans** [comment]
Okay! I'll try adding such a feature locally to verify that it resolves the issue and then hopefully submit a PR here. Thanks for the advice! 😁
