### ISSUE TITLE
My chrome get an ERROR when run raytrace-parallel-example..

### ISSUE THREAD

**Issue by Anehta** [rustwasm/wasm-bindgen#1772]
DOMException: Failed to execute 'postMessage' on 'Worker': #<Memory> could not be cloned.
    at imports.wbg.__widl_f_post_message_Worker (http://localhost:8080/raytrace_parallel.js:441:29)
    at web_sys::Worker::post_message::h672e1bc71a814a7f (wasm-function[360]:0x34c7a)
    at raytrace_parallel::pool::WorkerPool::spawn::he533279a22f15274 (wasm-function[135]:0x23fa9)
    at workerpool_new (wasm-function[232]:0x2eb94)
    at new WorkerPool (http://localhost:8080/raytrace_parallel.js:323:26)
    at run (http://localhost:8080/index.js:43:10)

in chrome

![image](https://user-images.githubusercontent.com/6553443/65217580-12401180-dae7-11e9-8caa-3a8f99026f3f.png)

**Comment by alexcrichton** [comment]
Thanks for the report! Currently Chrome doesn't have enough support for the threads proposal though to run this example, so it's expected to fail. Firefox nightly works though!

**Comment by ibaryshnikov** [comment]
There is a progress in Chrome, now it emits
```
RuntimeError: function signature mismatch
    at core::fmt::write::h625a870736ca0a24 (wasm-function[90]:0x16c52)
    at raytrace_parallel::pool::WorkerPool::spawn::h31ceda768aaab822 (wasm-function[124]:0x1d6fb)
    at workerpool_new (wasm-function[229]:0x28f72)
```
Version 79.0.3923.0 (Official Build) canary (64-bit)

**Comment by Aedron** [comment]
It works fine at **Chrome 79.0.3945.117 (macOS)**
