### ISSUE TITLE
map typescript default module

### ISSUE THREAD

**Issue by ctaggart** [rustwasm/wasm-bindgen#2064]
I'm having difficulty mapping the typescript module. The generated code creates:
``` js
const { ts } = require(String.raw`typescript`);
```
but I think it will work if it creates:
``` js
const ts = require(String.raw`typescript`);
```

I found #1006 fixed by #1106, but I couldn't get it to work. Here is lib.rs:
``` rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn greet() {
    log("hello node");
    log(&ts.getNodeMajorVersion());
    // log(&version);
}

// https://rustwasm.github.io/docs/wasm-bindgen/examples/console-log.html
#[wasm_bindgen]
extern {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

// https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/module.html
// default pr https://github.com/rustwasm/wasm-bindgen/pull/1106/files
#[wasm_bindgen(module = "typescript")]
extern {
    
    #[wasm_bindgen(js_name = default)]
    type Ts;
    static ts: Ts;

    #[wasm_bindgen(method)]
    fn getNodeMajorVersion(this: &Ts) -> String;

    // static version: String;
}
```
I've tried `#[wasm_bindgen(js_name = default)]` on `static ts: Ts` as well.

**Comment by Pauan** [comment]
You need to bind it like this:

```rust
#[wasm_bindgen(module = "typescript")]
extern {
    type Ts;

    #[wasm_bindgen(js_name = default)]
    static ts: Ts;

    #[wasm_bindgen(method)]
    fn getNodeMajorVersion(this: &Ts) -> String;

    // static version: String;
}
```

**Comment by Pauan** [comment]
Hmmm, actually, after checking the generated code, that looks for a `default` export.

I don't think we actually have any way to bind to the actual module right now.

**Comment by Pauan** [comment]
However, if you only need to bind to the properties (not the module itself), you can do this:

```rust
#[wasm_bindgen(module = "typescript")]
extern {
    fn getNodeMajorVersion() -> String;
}
```

That should work fine.

**Comment by ctaggart** [comment]
I do want to build to be able to bind to the module itself, access `ts.getNodeMajorVersion()` as well as `ts.version`. 

That suggested binding leads to this error:
```
Camerons-MacBook-Pro:wasm-game-of-life cameron$ ./run.sh 
hello node
buffer.js:693
    throw new ERR_INVALID_ARG_TYPE(
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type number
    at Function.byteLength (buffer.js:693:11)
    at passStringToWasm0 (/Users/cameron/tmp/wasm-game-of-life/pkg/wasm_game_of_life.js:41:24)
    at module.exports.__wbg_getNodeMajorVersion_13fd2c79e63df52c (/Users/cameron/tmp/wasm-game-of-life/pkg/wasm_game_of_life.js:62:16)
    at wasm-function[17]:26
    at wasm-function[40]:1
    at Object.<anonymous> (/Users/cameron/tmp/wasm-game-of-life/main.js:7:5)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
```

wasm_game_of_life.js:62 is the line with `passStringToWasm0` in:
``` js
module.exports.__wbg_getNodeMajorVersion_13fd2c79e63df52c = function(arg0) {
    var ret = getNodeMajorVersion();
    var ptr0 = passStringToWasm0(ret, wasm.__wbindgen_malloc, wasm.__wbindgen_realloc);
    var len0 = WASM_VECTOR_LEN;
    getInt32Memory0()[arg0 / 4 + 1] = len0;
    getInt32Memory0()[arg0 / 4 + 0] = ptr0;
};
```

**Comment by ctaggart** [comment]
I pushed the code here:
https://github.com/ctaggart/wasm-bindgen-2064/blob/master/src/lib.rs

**Comment by Pauan** [comment]
@ctaggart The problem with your code is that `getNodeMajorVersion()` returns `undefined` or a number, not a string. That's why you're getting that error.

You don't need to bind to the `typescript` module itself, you can just bind to the things exported by it:

```rust
#[wasm_bindgen(module = "typescript")]
extern {
    fn getNodeMajorVersion() -> Option<u32>;

    static version: String;
}
```

**Comment by ctaggart** [comment]
Works great @Pauan, thanks!

``` rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn greet() {
    log("hello node");
    if let Some(major_node_version) = getNodeMajorVersion() {
        log(&format!("Node major version: {}", &major_node_version));
    }
    log(&format!("TypeScript version: {}", &version.to_string()));
}

// https://rustwasm.github.io/docs/wasm-bindgen/examples/console-log.html
#[wasm_bindgen]
extern {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

// https://rustwasm.github.io/docs/wasm-bindgen/reference/attributes/on-js-imports/module.html
#[wasm_bindgen(module = "typescript")]
extern {
    fn getNodeMajorVersion() -> Option<u32>;
    static version: String;
}
```

greet() prints:
```
hello node
Node major version: 12
TypeScript version: 3.8.3
```
