### ISSUE TITLE
TypeError: Cannot read property 'stat' of undefined (examples/canvas)

### ISSUE THREAD

**Issue by Hirrolot** [rustwasm/wasm-bindgen#2193]
### Describe the Bug

`examples/canvas` doesn't work: when I open http://localhost:8080/, it begans loading forever. 

### Steps to Reproduce

```
git clone https://github.com/rustwasm/wasm-bindgen.git
cd examples/canvas
npm install

// A big tree of dependencies...

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@2.1.3
npm WARN optional Skipping failed optional dependency /watchpack-chokidar2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13
npm WARN optional Skipping failed optional dependency /webpack-dev-server/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.13
npm WARN canvas No repository field.
npm WARN canvas No license field.

npm run serve
> @ serve /home/hirrolot/Desktop/wasm-bindgen/examples/canvas
> webpack-dev-server

🧐  Checking for wasm-pack...

✅  wasm-pack is installed. 

ℹ️  Compiling your crate in development mode...

✖ ｢wdm｣: TypeError: Cannot read property 'stat' of undefined
    at WasmPackPlugin._compile (/home/hirrolot/Desktop/wasm-bindgen/examples/canvas/node_modules/@wasm-tool/wasm-pack-plugin/plugin.js:120:24)
    at _checkWasmPack.then (/home/hirrolot/Desktop/wasm-bindgen/examples/canvas/node_modules/@wasm-tool/wasm-pack-plugin/plugin.js:66:23)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/hirrolot/Desktop/wasm-bindgen/examples/canvas
ℹ ｢wdm｣: wait until bundle finished: /
^C
```

### Expected Behavior

https://rustwasm.github.io/wasm-bindgen/exbuild/canvas/

**Comment by alexcrichton** [comment]
This looks like it's a bug in webpack or the `WasmPackPlugin`, not in this crate. If this shows up in this crate itself, though, please let me know!

**Comment by Mromson** [comment]
Is this not relevant when the above-mentioned bug means that the listed example in this repo won't work?

**Comment by alexcrichton** [comment]
If this isn't working for you it's likely due to https://github.com/rustwasm/wasm-bindgen/issues/1227 where to guarantee examples run they need to be copied out first.

**Comment by naia-rs** [comment]
Copying out the example doesn't work for me :/
