### ISSUE TITLE
panicked at 'already borrowed: BorrowMutError'

### ISSUE THREAD

**Issue by graemer957** [rustwasm/wasm-bindgen#2562]
Hi 👋 

### Describe the Bug

I have found that under high load accessing Cloudflare KV and Cache API from Rust causes the following panic:
```rust
panicked at 'already borrowed: BorrowMutError',
/Users/graemer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-futures-0.4.23/src/lib.rs:133:39
```

I already raised a issue with them on their [cloudflare/rustwasm-worker-template](https://github.com/cloudflare/rustwasm-worker-template/issues/22), but they suggested you might be in a better place to help.

### Steps to Reproduce

A sample project to reproduce this can be found [cfw-borrowmuterror](https://github.com/graemer957/cfw-borrowmuterror). The sample project has two endpoints:
* `/js` which fetches the `foo` key using just JavaScript
* `/rs` which does the same, but using Rust

1. Update project to bind KV namespace `EXAMPLE_NS` on your account
2. Deploy this code to Cloudflare Workers
3. In `EXAMPLE_NS` ensure the `foo` key exists, the value can be whatever you like
4. Use `curl` to hit either the `/js` or `/rs` endpoint and ensure your value defined in (3) is returned.
5. Use `wrangler tail` to capture the logs from your deployed worker
6. To simulate load I have been using `wrk`, for example:
```bash
wrk -c 128 -t 4 -d 60s --latency https://<host>/rs
```

There are quite a few exceptions which do not generate useful logs, but if you are lucky:

```json
{"exceptions":[{"name":"Error","message":"The script will never generate a response.","timestamp":1621326408887}],"logs":[{"message":["panicked at 'already borrowed: BorrowMutError', /Users/graemer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-futures-0.4.23/src/lib.rs:133:39\n\nStack:\n\nError\n    at imports.wbg.__wbg_new_59cb74e423758ede (worker.js:288:19)\n    at <anonymous>:wasm-function[28]:0x3a77\n    at <anonymous>:wasm-function[240]:0x946b\n    at <anonymous>:wasm-function[64]:0x686b\n    at <anonymous>:wasm-function[85]:0x75f4\n    at <anonymous>:wasm-function[160]:0x8cd5\n    at <anonymous>:wasm-function[139]:0x88d5\n    at <anonymous>:wasm-function[162]:0x8d38\n    at <anonymous>:wasm-function[91]:0x78c0\n    at <anonymous>:wasm-function[60]:0x6539\n\n"],"level":"error","timestamp":1621326408887}]}
```

Applying the same load to the `/js` endpoint always works. Only the `/rs` endpoint exhibits the issue.

I can see on [L133](https://github.com/rustwasm/wasm-bindgen/blob/3cefe2c8246141fa32c169ccbaf0e49a07b6f056/crates/futures/src/lib.rs#L133):
```rust
let mut state = state.borrow_mut();
```
...and would love to be able to dig further, but at the current limits of my knowledge on how to proceed. Any help gratefully received.

### Expected Behavior

No panic occurs.

### Actual Behavior

Under higher loads the following panic is observed:
```rust
panicked at 'already borrowed: BorrowMutError',
/Users/graemer/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-futures-0.4.23/src/lib.rs:133:39
```

**Comment by alexcrichton** [comment]
How curious! Unfortunately I don't know how to set up a cloudflare environment or similar so the best I can offer is "debugging by reading code". Reading over this code I don't understand how this borrow can trip an error. Some questions I could ask are:

* If possible, can you get a stack trace with function names? If not, can you build a wasm binary with debugging information and send it plus a stack trace to me?
* Do you know if cloudflares fork of v8 futzes with when callbacks run or things like that? One way this *could* trip is if wasm is interrupted and a callback is run while wasm is run on the stack. I think that's not possible on the web, but cloudflare may be doing their own thing here.

Otherwise if you could get a reproduction without cloudflare (e.g. in a browser or on node) I can help debug more.

**Comment by graemer957** [comment]
Hey @alexcrichton, apologies for the delay in getting back to you. Let me see if I can get that additional debug information you wanted and in the mean-time ask Cloudflare the question you asked.

**Comment by samdenty** [comment]
I can reliable reproduce this as well @alexcrichton, how should I proceed to debug?

**Comment by samdenty** [comment]
Ok so I've managed to get a local build of wasm-bindgen-futures, compiling inside the cloudflare worker that's erroring.

I've narrowed it down to this function https://github.com/rustwasm/wasm-bindgen/blob/3c1f5a9e3ee197988ab9afe35d7244b751ad8cbb/crates/futures/src/task/singlethread.rs#L100

Calling the poll method, makes it recursively call the `run` function https://github.com/rustwasm/wasm-bindgen/blob/3c1f5a9e3ee197988ab9afe35d7244b751ad8cbb/crates/futures/src/task/singlethread.rs#L84

and because of this, `borrow_mut` fails. In my code I'm doing `future.shared()` so maybe this is causing this?

**Comment by samdenty** [comment]
the error stack doesn't reveal much:

```
Error
    at __wbg_new_abda76e883ba8a5f (shim.js:415:19)
    at console_error_panic_hook::hook::h36ed105c675de4f7 (wasm://wasm/00f1df7a:wasm-function[1750]:0x181a6e)
    at core::ops::function::Fn::call::h9f9f084f27f78c00 (wasm://wasm/00f1df7a:wasm-function[6876]:0x2046af)
    at std::panicking::rust_panic_with_hook::had8acafc277b06ff (wasm://wasm/00f1df7a:wasm-function[2361]:0x1a7e35)
    at std::panicking::begin_panic_handler::{{closure}}::h1f07988bb2cf1601 (wasm://wasm/00f1df7a:wasm-function[2952]:0x1c3341)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h9b10ea262b3bcf96 (wasm://wasm/00f1df7a:wasm-function[5362]:0x1fb990)
    at rust_begin_unwind (wasm://wasm/00f1df7a:wasm-function[4162]:0x1e79aa)
    at core::panicking::panic_fmt::h0498752af691fa0d (wasm://wasm/00f1df7a:wasm-function[4988]:0x1f6b8e)
    at core::result::unwrap_failed::hff7d8a43159e0958 (wasm://wasm/00f1df7a:wasm-function[3151]:0x1cacfc)
    at wasm_bindgen_futures::task::singlethread::Task::run::hdda06db3adb32b62 (wasm://wasm/00f1df7a:wasm-function[2200]:0x19f0be)
```

**Comment by Liamolucko** [comment]
> I've narrowed it down to this function
> 
> https://github.com/rustwasm/wasm-bindgen/blob/3c1f5a9e3ee197988ab9afe35d7244b751ad8cbb/crates/futures/src/task/singlethread.rs#L100
> 
> Calling the poll method, in my case makes it recursively call the `run` function with the same future
> 
> https://github.com/rustwasm/wasm-bindgen/blob/3c1f5a9e3ee197988ab9afe35d7244b751ad8cbb/crates/futures/src/task/singlethread.rs#L84
> 
> and because of this, `borrow_mut` fails.

That certainly seems like something odd is happening with Cloudflare's JS runtime, because as far as I can tell that should be impossible with a normal JS runtime.

`run` is only ever called from `QueueState::run_all`, which is only ever called from this closure:

https://github.com/rustwasm/wasm-bindgen/blob/3c1f5a9e3ee197988ab9afe35d7244b751ad8cbb/crates/futures/src/queue.rs#L81

That closure is then only ever used as a callback for `Promise::then`:

https://github.com/rustwasm/wasm-bindgen/blob/3c1f5a9e3ee197988ab9afe35d7244b751ad8cbb/crates/futures/src/queue.rs#L55

But, callbacks from `Promise::then` are always meant to be run in a new microtask, which should make it impossible for it to get called recursively. So, it looks like Cloudflare is somehow breaking that rule and calling the callback synchronously, leading to the recursive call.

> do you want me to give you the steps to reproduce inside a cloudflare worker?

That should be helpful, particularly if it can be done locally using [workerd](https://github.com/cloudflare/workerd).

**Comment by samdenty** [comment]
the reproduction I can come up with that shows the error:

```bash
git clone https://github.com/samdenty/github-icons
cd api
wrangler dev
```

Once it prompts, turn on local mode by pressing `L`. Then in postman fetch the URL `http://127.0.0.1:8787/facebook/yoga` (if you navigate to it in chrome, it won't work as it'll try to redirect to homepage)

**Comment by samdenty** [comment]
Interestingly enough sometimes I get this error:

```log
TypeError: Found invalid object in transferList
panicked at 'TypeError: Found invalid object in transferList', api/src/lib.rs:49:1

Stack:

Error:
    at he (/Users/samdenty/Projects/github-icons/api/build/worker/shim.mjs:17:1263)
    at console_error_panic_hook::hook::hfc8ebd4821eabe90 (wasm://wasm/00f1dd46:1:1579814)
    at core::ops::function::Fn::call::h3b927a197a89b48c (wasm://wasm/00f1dd46:1:2115137)
    at std::panicking::rust_panic_with_hook::had8acafc277b06ff (wasm://wasm/00f1dd46:1:1735855)
    at std::panicking::begin_panic_handler::{{closure}}::h1f07988bb2cf1601 (wasm://wasm/00f1dd46:1:1847921)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h9b10ea262b3bcf96 (wasm://wasm/00f1dd46:1:2079010)
    at rust_begin_unwind (wasm://wasm/00f1dd46:1:1997116)
    at core::panicking::panic_fmt::h0498752af691fa0d (wasm://wasm/00f1dd46:1:2059040)
    at core::panicking::panic_display::h2b50038d5ebc0e22 (wasm://wasm/00f1dd46:1:2009235)
    at wasm_bindgen_futures::future_to_promise::{{closure}}::{{closure}}::h973c0b5f38fe9ea0 (wasm://wasm/00f1dd46:1:107462)
```

**Comment by littledivy** [comment]
This is also happening with the Deno runtime (V8). 

I'm also using  `future.shared()` which might be causing it?

```
panicked at /home/divy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-futures-0.4.37/src/task/singlethread.rs:85:37:
already borrowed: BorrowMutError

Stack:

Error
    at __wbg_new_abda76e883ba8a5f (file:///home/divy/gh/littledivy/deno_graph/js/deno_graph_wasm.generated.js:407:19)
    at <anonymous> (file:///home/divy/gh/littledivy/deno_graph/js/deno_graph_wasm_bg.wasm:1:1733565)
    at <anonymous> (file:///home/divy/gh/littledivy/deno_graph/js/deno_graph_wasm_bg.wasm:1:1896441)
    at <anonymous> (file:///home/divy/gh/littledivy/deno_graph/js/deno_graph_wasm_bg.wasm:1:1991438)
    at <anonymous> (file:///home/divy/gh/littledivy/deno_graph/js/deno_graph_wasm_bg.wasm:1:1867142)
    at <anonymous> (file:///home/divy/gh/littledivy/deno_graph/js/deno_graph_wasm_bg.wasm:1:1991362)
    at <anonymous> (file:///home/divy/gh/littledivy/deno_graph/js/deno_graph_wasm_bg.wasm:1:1911615)
    at <anonymous> (file:///home/divy/gh/littledivy/deno_graph/js/deno_graph_wasm_bg.wasm:1:1582451)
    at <anonymous> (file:///home/divy/gh/littledivy/deno_graph/js/deno_graph_wasm_bg.wasm:1:1929769)
    at __wbg_adapter_48 (file:///home/divy/gh/littledivy/deno_graph/js/deno_graph_wasm.generated.js:240:8)
```

**Comment by stephanemagnenat** [comment]
I saw a similar error with Safari 17.10 using latest version 0.4.50. I saw it through error analytics in production so it is hard for me to point out the exact error, but it happened during app initialization.

Here is the error and backtrace:
```
panicked at /XXX/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wasm-bindgen-futures-0.4.50/src/task/singlethread.rs:103:37:\nalready borrowed: BorrowMutError",

Stack:
@YYY/book/book_web_advanced.js:1199:30
logError@YYY/book/book_web_advanced.js:38:23
book_web.wasm.wasm-function[__wbg_new_a4cfd341aa34b5b9 externref shim]@[wasm code]
book_web.wasm.wasm-function[book_web::analytics::report_panic::hca58147bde3856f8]@[wasm code]
book_web.wasm.wasm-function[std::panicking::rust_panic_with_hook::h33fe77d38d305ca3]@[wasm code]
book_web.wasm.wasm-function[std::panicking::begin_panic_handler::{{closure}}::h98de848d678bad07]@[wasm code]
book_web.wasm.wasm-function[std::sys::backtrace::__rust_end_short_backtrace::h2bcfc60c3cf0a312]@[wasm code]
book_web.wasm.wasm-function[rust_begin_unwind]@[wasm code]
book_web.wasm.wasm-function[core::panicking::panic_fmt::hde8b7aa66e2831e1]@[wasm code]
book_web.wasm.wasm-function[core::cell::panic_already_borrowed::hb8d645dce0969dae]@[wasm code]
book_web.wasm.wasm-function[wasm_bindgen_futures::queue::Queue::new::{{closure}}::h82824e04608c818a]@[wasm code]
book_web.wasm.wasm-function[<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h4111640887c7643b]@[wasm code]
book_web.wasm.wasm-function[closure8 externref shim]@[wasm code]
__wbg_adapter_53@YYY/book/book_web_advanced.js:293:33
real@YYY/book/book_web_advanced.js:179:21
```

**Comment by zoechi** [comment]
I just run into this in Dioxus 0.6.3 in Chrome 135 and Firefox 137 on Linux.
In my case it is caused by the use of `stream_throttle`

I get this error before the `BorrowedMutError`, which seems reasonable because time is known to not be implemented. 
When I remove the use of `stream_throttle` the `BorrowedMutError` is gone as well.

```
my_app-b6e40050406c56c2.js:1 panicked at library/std/src/sys/pal/wasm/../unsupported/time.rs:13:9:
time not implemented on this platform

Stack:

Error
    at http://127.0.0.1:41809/assets/my_app-b6e40050406c56c2.js:5:32227
    at logError (http://127.0.0.1:41809/assets/my_app-b6e40050406c56c2.js:1:21082)
    at imports.wbg.__wbg_new_8a6f238a6ece86ea (http://127.0.0.1:41809/assets/my_app-b6e40050406c56c2.js:5:32197)
    at my_app-05dc4c2ce192052a.wasm.__wbg_new_8a6f238a6ece86ea externref shim (http://127.0.0.1:41809/assets/my_app_bg-71fbdb6a01a25f8e.wasm:wasm-function[4475]:0x19d299)
    at my_app-05dc4c2ce192052a.wasm.console_error_panic_hook::hook::h0b6655e4ca6177ee (http://127.0.0.1:41809/assets/my_app_bg-71fbdb6a01a25f8e.wasm:wasm-function[922]:0xe58b1)
    at my_app-05dc4c2ce192052a.wasm.core::ops::function::Fn::call::hfeb1ce0dd5b5fda3 (http://127.0.0.1:41809/assets/my_app_bg-71fbdb6a01a25f8e.wasm:wasm-function[5639]:0x1a1c6f)
    at my_app-05dc4c2ce192052a.wasm.std::panicking::rust_panic_with_hook::hac5809f68b3a1dcb (http://127.0.0.1:41809/assets/my_app_bg-71fbdb6a01a25f8e.wasm:wasm-function[2302]:0x16c1c5)
    at my_app-05dc4c2ce192052a.wasm.std::panicking::begin_panic_handler::{{closure}}::h4de4715f4447af58 (http://127.0.0.1:41809/assets/my_app_bg-71fbdb6a01a25f8e.wasm:wasm-function[2631]:0x17bb41)
    at my_app-05dc4c2ce192052a.wasm.std::sys::backtrace::__rust_end_short_backtrace::hbe69dd6935672c1e (http://127.0.0.1:41809/assets/my_app_bg-71fbdb6a01a25f8e.wasm:wasm-function[5457]:0x1a15e8)
    at my_app-05dc4c2ce192052a.wasm.__rustc[eaa09f15cded1793]::rust_begin_unwind (http://127.0.0.1:41809/assets/my_app_bg-71fbdb6a01a25f8e.wasm:wasm-function[3905]:0x198c54)
```
