### ISSUE TITLE
"remaining data [25]" error during build when using wasm-bindgen-futures

### ISSUE THREAD

**Issue by ctiedt** [rustwasm/wasm-bindgen#2690]
I am trying to create an async function in Rust to later call it from JavaScript.
However, after adding `wasm-bindgen-futures` as a dependency, the `wasm-bindgen` command (`RUST_BACKTRACE=1 wasm-bindgen target/wasm32-unknown-unknown/debug/wasm_bindgen_futures_minimal_example.wasm --out-dir pkg --target web`) fails. The output is:

```
thread 'main' panicked at 'remaining data [25]', /home/clemens/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.74/src/descriptor.rs:109:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/625d5a693e4697bcafdd34fd1a38c281acabb8e9/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/625d5a693e4697bcafdd34fd1a38c281acabb8e9/library/std/src/panicking.rs:457:5
   2: wasm_bindgen_cli_support::descriptors::execute
   3: wasm_bindgen_cli_support::Bindgen::generate_output
   4: wasm_bindgen_cli_support::Bindgen::generate
   5: wasm_bindgen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Minimal example:

```rust
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub async fn main() {}
```

I am using `wasm-bindgen` version 0.2.78 and `wasm-bindgen-futures` version 0.4.28.

**Comment by ctiedt** [comment]
I was using a slightly older version of the CLI, but after updating to `wasm-bindgen-cli` version 0.2.78 I got a different error:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/clemens/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.78/src/js/binding.rs:379:26
stack backtrace:
   0: rust_begin_unwind
             at /rustc/25ec8273855fde2d72ae877b397e054de5300e10/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/25ec8273855fde2d72ae877b397e054de5300e10/library/core/src/panicking.rs:100:14
   2: core::panicking::panic
             at /rustc/25ec8273855fde2d72ae877b397e054de5300e10/library/core/src/panicking.rs:50:5
   3: wasm_bindgen_cli_support::js::binding::instruction
   4: wasm_bindgen_cli_support::js::binding::Builder::process
   5: wasm_bindgen_cli_support::js::Context::generate
   6: wasm_bindgen_cli_support::Bindgen::generate_output
   7: wasm_bindgen_cli_support::Bindgen::generate
   8: wasm_bindgen::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
