### ISSUE TITLE
wasm bindgen cli: Index out of bounds.

### ISSUE THREAD

**Issue by NicolasSabba** [rustwasm/wasm-bindgen#2697]
### Describe the Bug

 When i try to generate JS bindings for a wasm file wasm-bindgen crashes.

This error occurs in versions 0.2.77 (inclusive) or higher.

### Steps to Reproduce

Run:
`RUST_BACKTRACE=full wasm-bindgen "target/wasm32-unknown-unknown/release/(Name of your crate).wasm" --out-dir wasm --target no-modules --no-typescript`

Example project where the error occurs:
[Example project](https://git.sr.ht/~nik_codes/roguelikedev-2021)

### Expected Behavior

The command should generate JS bindings and place them in the out dir

### Actual Behavior

wasm bindgen cli crashes

Crash report:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/nicolas/.cargo/registry/src/github.com-1ecc6299db9ec823/wasm-bindgen-cli-support-0.2.78/src/descriptor.rs:205:15
stack backtrace:
   0:     0x5567e8045750 - std::backtrace_rs::backtrace::libunwind::trace::ha0ad43e8a952bfe7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5567e8045750 - std::backtrace_rs::backtrace::trace_unsynchronized::h6830419c0c4130dc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5567e8045750 - std::sys_common::backtrace::_print_fmt::h8f3516631ffa1ef5
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5567e8045750 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1640d5f0d93f618
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5567e8067b0c - core::fmt::write::h88012e1f01caeebf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/fmt/mod.rs:1115:17
   5:     0x5567e8042ee5 - std::io::Write::write_fmt::h360fa85b30182555
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/io/mod.rs:1665:15
   6:     0x5567e804770b - std::sys_common::backtrace::_print::ha1f00492f406a015
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5567e804770b - std::sys_common::backtrace::print::hd54561b13feb6af3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5567e804770b - std::panicking::default_hook::{{closure}}::h84fe124cd0864662
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:208:50
   9:     0x5567e80471e1 - std::panicking::default_hook::h5a8e74a76ce290a7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:225:9
  10:     0x5567e8047dd4 - std::panicking::rust_panic_with_hook::h67c812a4fe9d4c91
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:622:17
  11:     0x5567e80478b7 - std::panicking::begin_panic_handler::{{closure}}::h33f9c1b96af300d7
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:519:13
  12:     0x5567e8045c4c - std::sys_common::backtrace::__rust_end_short_backtrace::h51bae64be5921f0e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5567e8047819 - rust_begin_unwind
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
  14:     0x5567e7d842f1 - core::panicking::panic_fmt::h12a3a3c256485fca
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
  15:     0x5567e7d842b2 - core::panicking::panic_bounds_check::hf6f9b9870a3b97cf
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:69:5
  16:     0x5567e7dbab1a - wasm_bindgen_cli_support::descriptor::Descriptor::_decode::h5b8e15edb9b758a5
  17:     0x5567e7dbae0e - wasm_bindgen_cli_support::descriptor::Function::decode::h2cf7a9d03661cbc6
  18:     0x5567e7dba6be - wasm_bindgen_cli_support::descriptor::Descriptor::_decode::h5b8e15edb9b758a5
  19:     0x5567e7de81a9 - wasm_bindgen_cli_support::descriptors::execute::h5781538e4d5c096f
  20:     0x5567e7d9ed9d - wasm_bindgen_cli_support::Bindgen::generate_output::h111f88857734f325
  21:     0x5567e7d8585e - wasm_bindgen_cli_support::Bindgen::generate::h57c31382aeec6e09
  22:     0x5567e7d88ed0 - wasm_bindgen::main::h16e3ff016f7dcbf4
  23:     0x5567e7d86fe3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h48b677553b23876c
  24:     0x5567e7d86ff9 - std::rt::lang_start::{{closure}}::h56dee81c1d84245d
  25:     0x5567e80483da - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::ha9408abe89f69dc4
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/ops/function.rs:259:13
  26:     0x5567e80483da - std::panicking::try::do_call::h5b0cc9e9102acb65
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  27:     0x5567e80483da - std::panicking::try::hddc7f8229138b3ba
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  28:     0x5567e80483da - std::panic::catch_unwind::hfa401ff8bab2986e
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  29:     0x5567e80483da - std::rt::lang_start_internal::{{closure}}::h8163422320d11405
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:48
  30:     0x5567e80483da - std::panicking::try::do_call::hc742cc7bb4f0fb20
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:401:40
  31:     0x5567e80483da - std::panicking::try::ha37d8d2dd1acf7d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:365:19
  32:     0x5567e80483da - std::panic::catch_unwind::h8a5381d5ecf437bc
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panic.rs:434:14
  33:     0x5567e80483da - std::rt::lang_start_internal::h7e2cee8c90d4a4d3
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/rt.rs:45:20
  34:     0x5567e7d892d2 - main
  35:     0x7f7fc8a27565 - __libc_start_main
  36:     0x5567e7d84ace - _start
  37:                0x0 - <unknown>

```

### Additional Context

OS: Pop!_OS 21.04 x86_64

**Comment by Ameobea** [comment]
> this is likely due to a difference between the CLI and crate versions

Yeah that was indeed the problem.  It's weird, wasm-bindgen used to complain and abort the build if the versions didn't match up.

**Comment by alexcrichton** [comment]
That was a recent issue which has since been fixed, but it unfortunately leaked into a few different versions.
