### ISSUE TITLE
cant compile

### ISSUE THREAD

**Issue by tyoc213** [rustwasm/wasm-bindgen#2744]
### Describe the Bug

Can't run hello_world example

### Steps to Reproduce

1. git clone 
2. `cd examples/hello_world`
3. `pm audit fix --force`
4. `npm run serve`
5. 

```
$ npm run serve

> serve
> webpack serve

🧐  Checking for wasm-pack...

✅  wasm-pack is installed at /home/tyoc213/.cargo/bin/wasm-pack. 

ℹ️  Compiling your crate in development mode...

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.149:8080/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::9a99:375:9c0d:783c]:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/public' directory
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling hello_world v0.1.0 (/home/tyoc213/webassembly/wasm-bindgen/examples/hello_world)
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/cli-support/src/descriptor.rs:205:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 101
  full command: "/home/tyoc213/.cache/.wasm-pack/wasm-bindgen-e63eccbd87203048/wasm-bindgen" "/home/tyoc213/webassembly/wasm-bindgen/target/wasm32-unknown-unknown/debug/hello_world.wasm" "--out-dir" "/home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg" "--typescript" "--target" "bundler" "--out-name" "index" "--debug"
asset index.js 243 KiB [emitted] (name: main)
asset index.html 232 bytes [emitted]
runtime modules 26.9 KiB 12 modules
modules by path ./node_modules/ 161 KiB
  modules by path ./node_modules/webpack-dev-server/client/ 56.8 KiB 12 modules
  modules by path ./node_modules/webpack/hot/*.js 4.3 KiB 4 modules
  modules by path ./node_modules/html-entities/lib/*.js 81.3 KiB
    ./node_modules/html-entities/lib/index.js 7.74 KiB [built] [code generated]
    ./node_modules/html-entities/lib/named-references.js 72.7 KiB [built] [code generated]
    ./node_modules/html-entities/lib/numeric-unicode-map.js 339 bytes [built] [code generated]
    ./node_modules/html-entities/lib/surrogate-pairs.js 537 bytes [built] [code generated]
  ./node_modules/ansi-html-community/index.js 4.16 KiB [built] [code generated]
  ./node_modules/events/events.js 14.5 KiB [built] [code generated]
./index.js 266 bytes [built] [code generated]

ERROR in ./index.js 4:13-28
Module not found: Error: Can't resolve './pkg' in '/home/tyoc213/webassembly/wasm-bindgen/examples/hello_world'
resolve './pkg' in '/home/tyoc213/webassembly/wasm-bindgen/examples/hello_world'
  using description file: /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/package.json (relative path: ./pkg)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg is not a file
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg.wasm doesn't exist
      as directory
        existing directory /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg
          using description file: /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/package.json (relative path: ./pkg)
            using path: /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg/index
              using description file: /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/package.json (relative path: ./pkg/index)
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg/index doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg/index.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg/index.json doesn't exist
                .wasm
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg/index.wasm doesn't exist

webpack 5.65.0 compiled with 1 error in 663 ms
assets by path *.js 244 KiB
  asset index.js 243 KiB [emitted] (name: main)
  asset main.4470363f5e61f2e3d73d.hot-update.js 843 bytes [emitted] [immutable] [hmr] (name: main)
asset index.html 232 bytes [emitted]
asset main.4470363f5e61f2e3d73d.hot-update.json 28 bytes [emitted] [immutable] [hmr]
Entrypoint main 244 KiB = index.js 243 KiB main.4470363f5e61f2e3d73d.hot-update.js 843 bytes
cached modules 161 KiB [cached] 23 modules
runtime modules 26.9 KiB 12 modules

ERROR in ./index.js 4:13-28
Module not found: Error: Can't resolve './pkg' in '/home/tyoc213/webassembly/wasm-bindgen/examples/hello_world'
resolve './pkg' in '/home/tyoc213/webassembly/wasm-bindgen/examples/hello_world'
  using description file: /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/package.json (relative path: ./pkg)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg is not a file
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg.wasm doesn't exist
      as directory
        existing directory /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg
          using description file: /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/package.json (relative path: ./pkg)
            using path: /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg/index
              using description file: /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/package.json (relative path: ./pkg/index)
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg/index doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg/index.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg/index.json doesn't exist
                .wasm
                  Field 'browser' doesn't contain a valid alias configuration
                  /home/tyoc213/webassembly/wasm-bindgen/examples/hello_world/pkg/index.wasm doesn't exist

ERROR in Rust compilation.

webpack 5.65.0 compiled with 2 errors in 29 ms

```

### Expected Behavior

compile and see the code on browser

### Actual Behavior

Cant open example on http://localhost:8000/ Webassembly compiled with 2 errors

-------------------
Tried the command in other example

```
$ RUST_BACKTRACE=full /home/tyoc213/.cache/.wasm-pack/wasm-bindgen-e63eccbd87203048/wasm-bindgen /home/tyoc213/webassembly/wasm-bindgen/target/wasm32-unknown-unknown/debug/wasm_bindgen_paint.wasm --out-dir /home/tyoc213/webassembly/wasm-bindgen/examples/paint/pkg --typescript --target bundler --out-name index --debug
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', crates/cli-support/src/descriptor.rs:205:15
stack backtrace:
   0:           0x6ebef0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf42958820747a8ac
   1:           0x7221bc - core::fmt::write::h6f5ededa5074697e
   2:           0x6e97d5 - std::io::Write::write_fmt::hdb84dc6c28fda870
   3:           0x6ede6b - std::panicking::default_hook::{{closure}}::hb85a09d7e9a16432
   4:           0x6ed941 - std::panicking::default_hook::hdc924e74cb190bbb
   5:           0x6ee534 - std::panicking::rust_panic_with_hook::hd63b080e78590a80
   6:           0x6ee017 - std::panicking::begin_panic_handler::{{closure}}::h27bfba1f7e931f90
   7:           0x6ec38c - std::sys_common::backtrace::__rust_end_short_backtrace::h2cc025f6c95b1f82
   8:           0x6edf79 - rust_begin_unwind
   9:           0x4291a1 - core::panicking::panic_fmt::h9f5a85773697c5f5
  10:           0x429162 - core::panicking::panic_bounds_check::h70dd3fd6056304a0
  11:           0x45f9ea - wasm_bindgen_cli_support::descriptor::Descriptor::_decode::h9adc04c55179ba18
  12:           0x45f9bc - wasm_bindgen_cli_support::descriptor::Descriptor::_decode::h9adc04c55179ba18
  13:           0x45f9bc - wasm_bindgen_cli_support::descriptor::Descriptor::_decode::h9adc04c55179ba18
  14:           0x45fcce - wasm_bindgen_cli_support::descriptor::Function::decode::h81540754b760c003
  15:           0x45f58e - wasm_bindgen_cli_support::descriptor::Descriptor::_decode::h9adc04c55179ba18
  16:           0x48d079 - wasm_bindgen_cli_support::descriptors::execute::hf8840b1ee2325cbc
  17:           0x443c6d - wasm_bindgen_cli_support::Bindgen::generate_output::h9b68d0f02d04575e
  18:           0x42a72e - wasm_bindgen_cli_support::Bindgen::generate::h0bb72b73165f8801
  19:           0x42dda0 - wasm_bindgen::main::h68109d2e2053b319
  20:           0x42beb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::he92ef7ccf1d60268
  21:           0x42bec9 - std::rt::lang_start::{{closure}}::h1aac00108137e691
  22:           0x6eea90 - std::rt::lang_start_internal::hfee0032b3594c35b
  23:           0x42e1a2 - main

```

**Comment by jcande** [comment]
I am hitting the same problem. I was able to workaround it by cloning the wasm-bindgen repo and compiling the wasm-bindgen binary with `cargo build --all`. Placing it in (for me) ~/.cargo/wasm-bindgen let `npm run serve` continue and everything then worked as expected.

It seems like whatever issue the examples are triggering is fixed on the current branch but I don't know how to get npm (or is it cargo?) to use a different version of the wasm-bindgen binary.

**Comment by mtKeller** [comment]
I've experienced this on Windows 10 and in Windows 11 WSL2 with Ubuntu 20.04 with the Steps to Reproduce. jcande's work around is also not working for me unfortunately. :/
