### ISSUE TITLE
```web_sys::CssStyleDeclaration::set_property``` returns error ```NoModificationAllowedError```

### ISSUE THREAD

**Issue by NatanFreeman** [rustwasm/wasm-bindgen#2992]
### Describe the Bug

Unwrapping `set_property` on `CssStyleDeclaration` to change CSS property returns `NoModificationAllowedError` in browser console.
>panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(NoModificationAllowedError: Failed to execute 'setProperty' on 'CSSStyleDeclaration': These styles are computed, and therefore the '--color' property is read-only.
Error: Failed to execute 'setProperty' on 'CSSStyleDeclaration': These styles are computed, and therefore the '--color' property is read-only.
    at http://localhost:8088/property-error-f7bf6957bf4e8d6e.js:381:25
    at handleError (http://localhost:8088/property-error-f7bf6957bf4e8d6e.js:234:18)
    at imports.wbg.__wbg_setProperty_88447bf87ac638d7 (http://localhost:8088/property-error-f7bf6957bf4e8d6e.js:380:74)
    at web_sys::features::gen_CssStyleDeclaration::CssStyleDeclaration::set_property::h4c5b6c19e8e077c1 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[308]:0x39e43)
    at <property_error::main as yew::functional::FunctionProvider>::run::h99d7a21d1fa9c8f7 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[64]:0xd929)
    at <yew::functional::FunctionComponent<T> as yew::html::component::Component>::view::{{closure}}::h0abdf6cfb7da1c7e (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[2926]:0x99987)
    at scoped_tls_hkt::ScopedKeyMut<T>::set::{{closure}}::hf0ea5686308b08ad (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[3228]:0x9e56b)
    at scoped_tls_hkt::ScopedKeyMut<T>::replace::h9ae6f887f13148f7 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[898]:0x618a1)
    at scoped_tls_hkt::ScopedKeyMut<T>::set::hff249e5495a20252 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[1975]:0x862c5)
    at yew::functional::FunctionComponent<T>::with_hook_state::hdcd1cb18f384d579 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[899]:0x6196c))', src\main.rs:13:43

> Stack:

> Error
    at imports.wbg.__wbg_new_693216e109162396 (http://localhost:8088/property-error-f7bf6957bf4e8d6e.js:303:21)
    at console_error_panic_hook::Error::new::h7b5b676a77d38c82 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[3244]:0x9e928)
    at console_error_panic_hook::hook_impl::h08ccc5d962b73ce3 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[286]:0x37aa2)
    at console_error_panic_hook::hook::h53cb4381f46a5685 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[3606]:0xa37d6)
    at core::ops::function::Fn::call::hd0eb82e0dbf70af2 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[2993]:0x9ab32)
    at std::panicking::rust_panic_with_hook::h8888bbc201384d7b (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[737]:0x58ef7)
    at std::panicking::begin_panic_handler::{{closure}}::hea311ea2bd92a293 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[1326]:0x73694)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h7df6c1a4b8949645 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[4139]:0xa87be)
    at rust_begin_unwind (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[3438]:0xa14ee)
    at core::panicking::panic_fmt::h18b15be283411c65 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[3484]:0xa1ee5)

#### Cargo.toml

```toml
[package]
name = "property-error"
version = "0.1.0"
edition = "2021"

[dependencies]
yew="0.19.3"
gloo-utils="0.1.4"
web-sys = {version="0.3.58", features=["CssStyleDeclaration"]}
```

#### main.rs
```rust
use gloo_utils::{document, window};
use yew::prelude::*;

#[function_component(Main)]
pub fn main(_props: &()) -> Html {
    let root = document().query_selector(":root").unwrap().unwrap();

    let style = window().get_computed_style(&root).unwrap().unwrap();

    let progress = style.get_property_value("--color").unwrap();
    println!("{progress}");

    style.set_property("--color", "blue").unwrap();

    return html! {
        <>
            <h1 id="style">{"Hello, World!"}</h1>
        </>
    };
}

fn main() {
    let _ = yew::start_app::<Main>();
}
```
#### index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Property error</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta charset="utf-8" />
    <link data-trunk rel="css" href="style.css" />
  </head>
</html>
```

#### style.css
```css
:root {
    --color: red
}

#style {
    color: red;
}
```

- Run `trunk serve`
- Go to http://localhost:8080/ on chromium.
- Aforementioned runtime error occurs.

[test case](https://github.com/NatanFreeman/property-error)

### Expected Behavior

The expected behavior is for the `--color` CSS property to be set to black. Resulting in the "Hello, World!" header to render as black.

### Actual Behavior

Full error:
> property-error-f7bf6957bf4e8d6e.js:297 panicked at 'called `Result::unwrap()` on an `Err` value: JsValue(NoModificationAllowedError: Failed to execute 'setProperty' on 'CSSStyleDeclaration': These styles are computed, and therefore the '--color' property is read-only.
Error: Failed to execute 'setProperty' on 'CSSStyleDeclaration': These styles are computed, and therefore the '--color' property is read-only.
    at http://localhost:8088/property-error-f7bf6957bf4e8d6e.js:381:25
    at handleError (http://localhost:8088/property-error-f7bf6957bf4e8d6e.js:234:18)
    at imports.wbg.__wbg_setProperty_88447bf87ac638d7 (http://localhost:8088/property-error-f7bf6957bf4e8d6e.js:380:74)
    at web_sys::features::gen_CssStyleDeclaration::CssStyleDeclaration::set_property::h4c5b6c19e8e077c1 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[308]:0x39e43)
    at <property_error::main as yew::functional::FunctionProvider>::run::h99d7a21d1fa9c8f7 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[64]:0xd929)
    at <yew::functional::FunctionComponent<T> as yew::html::component::Component>::view::{{closure}}::h0abdf6cfb7da1c7e (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[2926]:0x99987)
    at scoped_tls_hkt::ScopedKeyMut<T>::set::{{closure}}::hf0ea5686308b08ad (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[3228]:0x9e56b)
    at scoped_tls_hkt::ScopedKeyMut<T>::replace::h9ae6f887f13148f7 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[898]:0x618a1)
    at scoped_tls_hkt::ScopedKeyMut<T>::set::hff249e5495a20252 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[1975]:0x862c5)
    at yew::functional::FunctionComponent<T>::with_hook_state::hdcd1cb18f384d579 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[899]:0x6196c))', src\main.rs:13:43

> Stack:

> Error
    at imports.wbg.__wbg_new_693216e109162396 (http://localhost:8088/property-error-f7bf6957bf4e8d6e.js:303:21)
    at console_error_panic_hook::Error::new::h7b5b676a77d38c82 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[3244]:0x9e928)
    at console_error_panic_hook::hook_impl::h08ccc5d962b73ce3 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[286]:0x37aa2)
    at console_error_panic_hook::hook::h53cb4381f46a5685 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[3606]:0xa37d6)
    at core::ops::function::Fn::call::hd0eb82e0dbf70af2 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[2993]:0x9ab32)
    at std::panicking::rust_panic_with_hook::h8888bbc201384d7b (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[737]:0x58ef7)
    at std::panicking::begin_panic_handler::{{closure}}::hea311ea2bd92a293 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[1326]:0x73694)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h7df6c1a4b8949645 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[4139]:0xa87be)
    at rust_begin_unwind (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[3438]:0xa14ee)
    at core::panicking::panic_fmt::h18b15be283411c65 (http://localhost:8088/property-error-c62aa4c61a850ed4_bg.wasm:wasm-function[3484]:0xa1ee5)
> property-error-c62aa4c61a850ed4_bg.wasm:0xa8cc7 Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (property-error-c62aa4c61a850ed4_bg.wasm:0xa8cc7)
    at rust_panic (property-error-c62aa4c61a850ed4_bg.wasm:0xa64e7)
    at std::panicking::rust_panic_with_hook::h8888bbc201384d7b (property-error-c62aa4c61a850ed4_bg.wasm:0x58f22)
    at std::panicking::begin_panic_handler::{{closure}}::hea311ea2bd92a293 (property-error-c62aa4c61a850ed4_bg.wasm:0x73694)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h7df6c1a4b8949645 (property-error-c62aa4c61a850ed4_bg.wasm:0xa87be)
    at rust_begin_unwind (property-error-c62aa4c61a850ed4_bg.wasm:0xa14ee)
    at core::panicking::panic_fmt::h18b15be283411c65 (property-error-c62aa4c61a850ed4_bg.wasm:0xa1ee5)
    at core::result::unwrap_failed::he84b58f6b44a7df4 (property-error-c62aa4c61a850ed4_bg.wasm:0x79f90)
    at core::result::Result<T,E>::unwrap::h0dc370ea4d80a8a0 (property-error-c62aa4c61a850ed4_bg.wasm:0x7584b)
    at <property_error::main as yew::functional::FunctionProvider>::run::h99d7a21d1fa9c8f7 (property-error-c62aa4c61a850ed4_bg.wasm:0xd94b)
> Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

### Additional Context
`rustup`: 1.24.3
`cargo`: 1.62.0
`trunk`: 0.15.0

**Comment by jonboj** [comment]
Looking at the snippet. `style` is obtained with `let style = window().get_computed_style(&root).unwrap().unwrap();` 
MDN states in section [CSSStyleDeclaration](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration)
 "_Via [Window.getComputedStyle()](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle), which exposes the CSSStyleDeclaration object as a read-only interface._"
`NoModificationAllowedError` could origin from applying `.set_property` on a read-only interface.

**Comment by jonboj** [comment]
@NatanFreeman From MDN, in JS like second method in the list [document.styleSheets](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration), also shown in the example further down same page. This needs then to be converted into Rust with api calls through `web-sys` api [Document.style_sheets](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Document.html#method.style_sheets).

**Comment by jonboj** [comment]
@NatanFreeman A cast from `web_sys::StyleSheet` to `web_sys::CssStyleSheet` is need. The inheritance is shown at MDN [CSSStyleSheet](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet). Also reflected in the `web-sys` api [AsRef for CssStyleSheet](https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.StyleSheet.html#impl-AsRef%3CStyleSheet%3E-for-CssStyleSheet).

**Comment by NatanFreeman** [comment]
@jonboj  the cast you've demonstrated converts a `web_sys::CssStyleSheet` to `web_sys::StyleSheet`. The equivalent to `Document.styleSheets` being `web_sys::Document::style_sheets` returns `web_sys::StyleSheet` instead of `web_sys::CssStyleSheet`. How do I cast the other way around? From `web_sys::StyleSheet` to `web_sys::CssStyleSheet`?

**Comment by Liamolucko** [comment]
You can use [`dyn_into`](https://docs.rs/wasm-bindgen/latest/wasm_bindgen/trait.JsCast.html#method.dyn_into) (or [`dyn_ref`](https://docs.rs/wasm-bindgen/latest/wasm_bindgen/trait.JsCast.html#method.dyn_ref)). They'll return an `Option<CssStyleSheet>`, though, since a `StyleSheet` isn't guaranteed to be an instance of `CssStyleSheet`.

**Comment by Liamolucko** [comment]
The WebIDL for `StyleSheetList` seems to be outdated, though - [the up-to-date spec](https://www.w3.org/TR/cssom-1/#the-stylesheetlist-interface) says that it should only contain `CSSStyleSheet`s.

**Comment by NatanFreeman** [comment]
How do I access `dyn_into`? The following code returns this error.
```rust
use core::result::Result;
use gloo_utils::document;
use web_sys::CssStyleSheet;
use yew::prelude::*;

#[function_component(Main)]
pub fn main(_props: &()) -> Html {
    let style_object = document().style_sheets().item(0).unwrap();
    let style_object: Result<CssStyleSheet, _> = style_object.dyn_into();

    return html! {
        <>
            <h1 id="style">{"Hello, World!"}</h1>
        </>
    };
}

fn main() {
    let _ = yew::start_app::<Main>();
}
```
> error[E0599]: no method named `dyn_into` found for struct `StyleSheet` in the current scope
> error[E0599]: no method named `dyn_into` found for struct `StyleSheet` in the current scope
  --> src\main.rs:9:63
   |
9  |     let style_object: Result<CssStyleSheet, _> = style_object.dyn_into();
   |                                                               ^^^^^^^^ method not found in `StyleSheet`
   |
  ::: C:\Users\natan\.cargo\registry\src\github.com-1ecc6299db9ec823\wasm-bindgen-0.2.81\src\cast.rs:43:8
   |
43 |     fn dyn_into<T>(self) -> Result<T, Self>
   |        -------- the method is available for `StyleSheet` here
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
1  | use wasm_bindgen::cast::JsCast;
   |

Attempting to `use wasm_bindgen::cast::JsCast;` as the error suggests results in this:
> error[E0603]: module `cast` is private
>   --> src\main.rs:3:19
   |
3  | use wasm_bindgen::cast::JsCast;
   |                   ^^^^ private module
   |
note: the module `cast` is defined here
  --> C:\Users\natan\.cargo\registry\src\github.com-1ecc6299db9ec823\wasm-bindgen-0.2.81\src\lib.rs:69:1
   |
69 | mod cast;
   | ^^^^^^^^^

**Comment by jonboj** [comment]
To me `use wasm_bindgen::cast::JsCast;` looks incorrect. Instead try "[use wasm-bind::JsCast;](https://github.com/rustwasm/wasm-bindgen/blob/main/examples/canvas/src/lib.rs#L3)"

**Comment by NatanFreeman** [comment]
That worked. How do I now get a `web_sys::CssStyleDeclaration` from a `web_sys::CssRule` as shown in the [MDN example](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration)?

**Comment by Liamolucko** [comment]
You need to cast it to a `CssStyleRule` first. That's because not all CSS rules are style rules; they could be `@import`s or something.

For it to work you'll need to make sure the rule actually applies to `:root` though (either by hand-crafting the stylesheet or inserting a new one with [`CSSStyleSheet.insertRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule)).

**Comment by NatanFreeman** [comment]
It works now! I uploading the fix the the aforementioned [repo](https://github.com/NatanFreeman/property-error). Thanks to everyone who helped me get to the bottom of this. 🦀🦀🦀
