### ISSUE TITLE
Error build examples/wasm-in-web-worker

### ISSUE THREAD

**Issue by AlbanMinassian** [rustwasm/wasm-bindgen#2993]
### Describe the Bug

```bash
wasm-bindgen/examples/wasm-in-web-worker on  main [!] is 📦 v0.1.0 via 🦀 v1.61.0 
❯ sh ./build.sh 
thread 'main' panicked at 'assertion failed: mid <= self.len()', crates/cli-support/src/decode.rs:43:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 101
  full command: "/home/alban/.cache/.wasm-pack/wasm-bindgen-e0094da74c1e9817/wasm-bindgen" "/home/alban/programs/wasm-bindgen/target/wasm32-unknown-unknown/release/wasm_in_web_worker.wasm" "--out-dir" "/home/alban/programs/wasm-bindgen/examples/wasm-in-web-worker/www/pkg" "--typescript" "--target" "no-modules"
```

### Steps to Reproduce

0. `wasm-pack --version` => wasm-pack 0.10.3
1. `git clone https://github.com/rustwasm/wasm-bindgen.git wasm-bindgen-clean`
2. `cd wasm-bindgen-clean/examples/wasm-in-web-worker`
3. `sh ./build.sh`

### Expected Behavior

Command must finish without error

### Actual Behavior

```bash
wasm-bindgen/examples/wasm-in-web-worker on  main [!] is 📦 v0.1.0 via 🦀 v1.61.0 
❯ sh ./build.sh 
+ wasm-pack build --out-dir www/pkg --target no-modules
[INFO]: Checking for the Wasm target...
[INFO]: Compiling to Wasm...
   Compiling proc-macro2 v1.0.40
   Compiling quote v1.0.20
     .
     .
   Compiling wasm-bindgen v0.2.81 (/home/alban/programs/wasm-bindgen)
   Compiling wasm-bindgen-backend v0.2.81 (/home/alban/programs/wasm-bindgen/crates/backend)
   Compiling wasm-bindgen-macro-support v0.2.81 (/home/alban/programs/wasm-bindgen/crates/macro-support)
   Compiling wasm-bindgen-macro v0.2.81 (/home/alban/programs/wasm-bindgen/crates/macro)
   Compiling js-sys v0.3.58 (/home/alban/programs/wasm-bindgen/crates/js-sys)
   Compiling web-sys v0.3.58 (/home/alban/programs/wasm-bindgen/crates/web-sys)
   Compiling wasm-in-web-worker v0.1.0 (/home/alban/programs/wasm-bindgen/examples/wasm-in-web-worker)
    Finished release [optimized] target(s) in 24.61s
[WARN]: :-) origin crate has no README
[INFO]: Installing wasm-bindgen...
thread 'main' panicked at 'assertion failed: mid <= self.len()', crates/cli-support/src/decode.rs:43:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 101
  full command: "/home/alban/.cache/.wasm-pack/wasm-bindgen-e0094da74c1e9817/wasm-bindgen" "/home/alban/programs/wasm-bindgen/target/wasm32-unknown-unknown/release/wasm_in_web_worker.wasm" "--out-dir" "/home/alban/programs/wasm-bindgen/examples/wasm-in-web-worker/www/pkg" "--typescript" "--target" "no-modules"

```

### Additional Context

Ubuntu 22.04 LTS
same error if rust 1.6.2

**Comment by Liamolucko** [comment]
This is happening because the `main` branch of `wasm-bindgen` has changed its internal format since 0.2.81 (specifically in #2954), but `wasm-pack` is still using 0.2.81. The easiest way to work around this is to go back to 0.2.81:

```sh
git checkout 0.2.81
sh ./build.sh # assuming you're already in the examples/wasm-in-web-worker folder
```

If you want to use the git version, you can build the CLI yourself and add it to PATH so that it will be picked up by `wasm-pack`:

```sh
cargo build -p wasm-bindgen-cli --bin wasm-bindgen
# again assuming that you're in the examples/wasm-in-web-worker folder;
# if not, replace ../../ with the path to the wasm-bindgen repo.
export PATH="../../target/debug:$PATH"
./build.sh
```

There should probably be a better error message for this, though.

**Comment by AlbanMinassian** [comment]
Thank, it's now ok
