### ISSUE TITLE
js_sys::Function argument to async fn is undefined

### ISSUE THREAD

**Issue by marianoguerra** [rustwasm/wasm-bindgen#3167]
### Describe the Bug

when passing a js function as parameter to a rust async fn as described [here](https://rustwasm.github.io/docs/wasm-bindgen/reference/receiving-js-closures-in-rust.html) the value is undefined

it works for "sync" functions

### Steps to Reproduce

1. Clone this repository: https://github.com/marianoguerra-atik/wasmbindgen_bug_async_fn_arg
2. Run `make run` or follow instructions in the README

### Expected Behavior

it should print:

```
[Function: report]
info! hello sync
call_fn_sync result
[Function: report]
info! hello async
call_fn_async result
```

### Actual Behavior

it prints:

```
[Function: report]
info! hello sync
call_fn_sync result
undefined
TypeError: Cannot read properties of undefined (reading 'call')
    at file:///home/mariano/src/rust/experiments/wasmbindgen_bug_async_fn_arg/pkg/wasmbindgen_bug_async_fn_arg.js:197:36
    at handleError (file:///home/mariano/src/rust/experiments/wasmbindgen_bug_async_fn_arg/pkg/wasmbindgen_bug_async_fn_arg.js:134:18)
    at imports.wbg.__wbg_call_168da88779e35f61 (file:///home/mariano/src/rust/experiments/wasmbindgen_bug_async_fn_arg/pkg/wasmbindgen_bug_async_fn_arg.js:196:67)
    at <anonymous> (file:///home/mariano/src/rust/experiments/wasmbindgen_bug_async_fn_arg/pkg/wasmbindgen_bug_async_fn_arg_bg.wasm:1:18727)
    at <anonymous> (file:///home/mariano/src/rust/experiments/wasmbindgen_bug_async_fn_arg/pkg/wasmbindgen_bug_async_fn_arg_bg.wasm:1:10612)
    at <anonymous> (file:///home/mariano/src/rust/experiments/wasmbindgen_bug_async_fn_arg/pkg/wasmbindgen_bug_async_fn_arg_bg.wasm:1:15565)
    at <anonymous> (file:///home/mariano/src/rust/experiments/wasmbindgen_bug_async_fn_arg/pkg/wasmbindgen_bug_async_fn_arg_bg.wasm:1:11637)
    at <anonymous> (file:///home/mariano/src/rust/experiments/wasmbindgen_bug_async_fn_arg/pkg/wasmbindgen_bug_async_fn_arg_bg.wasm:1:19954)
    at __wbg_adapter_10 (file:///home/mariano/src/rust/experiments/wasmbindgen_bug_async_fn_arg/pkg/wasmbindgen_bug_async_fn_arg.js:75:10)
    at real (file:///home/mariano/src/rust/experiments/wasmbindgen_bug_async_fn_arg/pkg/wasmbindgen_bug_async_fn_arg.js:60:20)
call_fn_async result
```

### Additional Context

rust 1.65
wasm-pack 0.10.3
library versions in Cargo.toml

**Comment by marianoguerra** [comment]
The bug happens both with old style functions and arrow functions (both reproduced in the repo)
