### ISSUE TITLE
[TEST FAIL] wasm::Date::to_locale_time_string fails due to whitespace character

### ISSUE THREAD

**Issue by SoulSharer** [rustwasm/wasm-bindgen#3181]
### Describe the Bug

Test fails due to whitespace character mismatch, 0x2F20 is returned from js side, is it an intended behavior?

```
failures:

---- wasm::Date::to_locale_time_string output ----
    error output:
        panicked at 'assertion failed: `(left == right)`
          left: `JsValue("11:15:30 PM")`,
         right: `"11:15:30 PM"`', crates\js-sys\tests\wasm\Date.rs:486:5

        Stack:

        Error
            at E:\Projects\Web\wasm-bindgen\target\wasm32-unknown-unknown\wbg-tmp\wasm-bindgen-test.js:1103:17
            at logError (E:\Projects\Web\wasm-bindgen\target\wasm32-unknown-unknown\wbg-tmp\wasm-bindgen-test.js:247:18)
            at module.exports.__wbg_new_abda76e883ba8a5f (E:\Projects\Web\wasm-bindgen\target\wasm32-unknown-unknown\wbg-tmp\wasm-bindgen-test.js:1102:65)
            at console_error_panic_hook::Error::new::ha28b1d9a37de7e4a (wasm://wasm/0153702e:wasm-function[13400]:0x373fe1)
            at console_error_panic_hook::hook_impl::hd72b67ab465d9da2 (wasm://wasm/0153702e:wasm-function[2304]:0x1c8876)
            at console_error_panic_hook::hook::hf58318d54a6fe5b5 (wasm://wasm/0153702e:wasm-function[15133]:0x38adec)
            at core::ops::function::Fn::call::h63192f4ab084032b (wasm://wasm/0153702e:wasm-function[13229]:0x3715ac)
            at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0153702e:wasm-function[4865]:0x27bbb9)
            at std::panicking::begin_panic_handler::{{closure}}::hdcfc819ce836829e (wasm://wasm/0153702e:wasm-function[6945]:0x2d8443)
            at std::sys_common::backtrace::__rust_end_short_backtrace::h53cabafab5b09ada (wasm://wasm/0153702e:wasm-function[16578]:0x39b715)



    JS exception that was thrown:
        RuntimeError: unreachable
            at __rust_start_panic (wasm://wasm/0153702e:wasm-function[18836]:0x3ad176)
            at rust_panic (wasm://wasm/0153702e:wasm-function[17069]:0x3a0638)
            at std::panicking::rust_panic_with_hook::h70a0e195f4db2a29 (wasm://wasm/0153702e:wasm-function[4865]:0x27bbe4)
            at std::panicking::begin_panic_handler::{{closure}}::hdcfc819ce836829e (wasm://wasm/0153702e:wasm-function[6945]:0x2d8443)
            at std::sys_common::backtrace::__rust_end_short_backtrace::h53cabafab5b09ada (wasm://wasm/0153702e:wasm-function[16578]:0x39b715)
            at rust_begin_unwind (wasm://wasm/0153702e:wasm-function[10755]:0x342754)
            at core::panicking::panic_fmt::h751be80779d42b53 (wasm://wasm/0153702e:wasm-function[14143]:0x37e4b6)
            at core::panicking::assert_failed_inner::h927c1f720bb46d31 (wasm://wasm/0153702e:wasm-function[2287]:0x1c6db3)
            at core::panicking::assert_failed::h24175c0f6746c097 (wasm://wasm/0153702e:wasm-function[4174]:0x254953)
            at wasm::Date::to_locale_time_string::hfb160dfa15b2701f (wasm://wasm/0153702e:wasm-function[2356]:0x1cd9f5)

failures:

    wasm::Date::to_locale_time_string
```

### Steps to Reproduce

Run *js-sys* tests on latest main. (a8695bb)

### Expected Behavior

Test should pass.

### Actual Behavior

Test fails to pass due to different whitespace characters, **to_locale_time_string** returns *0x2F20* and test tries to compare it with *0x20*.

### Additional Context
Windows 10 21H2 (19044.2251)
Firefox 107.0.1 (Windows 64-Bit)
Geckodriver v0.32.0-win64

**Comment by Liamolucko** [comment]
I can't reproduce this - when I try this locally, Firefox uses a regular 0x20 space. Either way, though, that would just be Firefox changing the behaviour of its version of `toLocaleTimeString`, not any problem with `wasm-bindgen`.

**Comment by SoulSharer** [comment]
Yeah it does seem that a particular version of the Firefox browser exhibits this behavior.
I just checked - turns out Firefox is not chromium based, that explains a lot.
