### ISSUE TITLE
In wasm-bindgen 0.2.84 version, webpack cannot generate wasm files

### ISSUE THREAD

**Issue by linzhipeng98** [rustwasm/wasm-bindgen#3276]
### Steps to Reproduce
I created a repo with the problem [here](https://github.com/linzhipeng98/wasm-bindgen-webpack)

Step1:
run `npm run i`

Step2:
run `wasm-pack build`

Step3:
run `npm run build`

A dist dir contain index.js and wasm file will be generated in the project root; It is expected behavior.

When i change the wasm-bindgen version to **0.2.84** and run
`rm -r pkg && wasm-pack build && npm run build`

In dist dir, webpack doesn't generate wasm files.

**Comment by hschimke** [comment]
I've noticed this as well, additionally: setting the version of wasm-bindgen back to 83 isn't respected for some reason, and cargo continues building with 84 regardless.

**Comment by AlexTMjugador** [comment]
I can reproduce this issue on my project too. Trying to use the WASM module in a development server throws a `wasm is undefined` exception.

**Comment by Liamolucko** [comment]
This seems to be a bug in Webpack, triggered by #3152. As a workaround, switching to dynamically importing the wasm-bindgen shim fixes it for some reason.

**Comment by Liamolucko** [comment]
It turns out this is happening because `wasm-pack` sets `"sideEffects": false` for `wasm-bindgen` generated code, which is a Webpack-specific flag that tells Webpack it can remove any code whose only impact is a side effect. In #3152, I unwittingly made initialisation rely on side effects, causing this problem.

(So, it's not a Webpack bug, I was a bit quick to assume that.)

I've opened rustwasm/wasm-pack#1224 to fix this. @alexcrichton or @drager, could you take a look at that PR?

**Comment by alexcrichton** [comment]
Ah sorry, I don't manage the `wasm-pack` repository myself.

**Comment by drager** [comment]
> It turns out this is happening because `wasm-pack` sets `"sideEffects": false` for `wasm-bindgen` generated code, which is a Webpack-specific flag that tells Webpack it can remove any code whose only impact is a side effect. In #3152, I unwittingly made initialisation rely on side effects, causing this problem.
> 
> (So, it's not a Webpack bug, I was a bit quick to assume that.)
> 
> I've opened [rustwasm/wasm-pack#1224](https://github.com/rustwasm/wasm-pack/pull/1224) to fix this. @alexcrichton or @drager, could you take a look at that PR?

Yeah, I will take a look soon. Thanks for looking into and fixing it!

**Comment by cryptoquick** [comment]
I tried setting everything back to 0.2.83, by running these steps in this order (after some trial and error):

```
cargo update -p wasm-bindgen-test --precise 0.3.33
cargo update -p wasm-bindgen-futures --precise 0.4.33
cargo update -p web-sys --precise 0.3.60
cargo update -p js-sys --precise 0.3.60
cargo update -p wasm-bindgen --precise 0.2.83
```

And then built it with rustc 1.67.1, making sure that the old versions were indeed the ones that were compiled...

But it still didn't solve the issue I ran into in #3306.

**Comment by Liamolucko** [comment]
> I tried setting everything back to 0.2.83, by running these steps in this order (after some trial and error):
> 
> ```
> cargo update -p wasm-bindgen-test --precise 0.3.33
> cargo update -p wasm-bindgen-futures --precise 0.4.33
> cargo update -p web-sys --precise 0.3.60
> cargo update -p js-sys --precise 0.3.60
> cargo update -p wasm-bindgen --precise 0.2.83
> ```
> 
> And then built it with rustc 1.67.1, making sure that the old versions were indeed the ones that were compiled...
> 
> But it still didn't solve the issue I ran into in #3306.

I can't reproduce this. Could you give more detailed instructions?

**Comment by cryptoquick** [comment]
> > I tried setting everything back to 0.2.83, by running these steps in this order (after some trial and error):
> > ```
> > cargo update -p wasm-bindgen-test --precise 0.3.33
> > cargo update -p wasm-bindgen-futures --precise 0.4.33
> > cargo update -p web-sys --precise 0.3.60
> > cargo update -p js-sys --precise 0.3.60
> > cargo update -p wasm-bindgen --precise 0.2.83
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And then built it with rustc 1.67.1, making sure that the old versions were indeed the ones that were compiled...
> > But it still didn't solve the issue I ran into in #3306.
> 
> I can't reproduce this. Could you give more detailed instructions?

I've updated and uploaded my MRE:
https://github.com/cryptoquick/wasm-bindgen-mre

**Comment by Liamolucko** [comment]
> I've updated and uploaded my MRE:
> 
> https://github.com/cryptoquick/wasm-bindgen-mre
> 
> 
> 
> I've made a few more changes, up to here: https://github.com/cryptoquick/wasm-bindgen-mre/commit/ee313c078b464d0d255e0158385e8f15c7fe879f
> 
> 
> 
> Still not working, same error as in README, not sure what else I can do...
> 
> 
> 
> I'm sure the cache is clearing too, since each time, I test with a different port on my local server.

That repo isn't demonstrating the original issue that you had in #3306, it's a completely separate issue which is occurring because you're not running `await init()` before using the wasm exports on `--target web`, as people already pointed out in #3306.

The *original* problem was with `--target bundler`, not `--target web`, and *that's* the issue that I believe is the same as this one and wasn't present in 0.2.83.

**Comment by kleinesfilmroellchen** [comment]
I have this exact issue, as soon as I upgrade to web_sys 0.3.61 from 0.3.60 any call to a Rust function from JavaScript results in an undefined error like:

```
bootstrap.js:2 Error importing `index.js`: TypeError: Cannot read properties of undefined (reading 'on_assembly_change')
    at Module.on_assembly_change (spcasm_web_bg.js:269:10)
    at eval (index.js:36:46)
    at __webpack_require__.a (bootstrap.js:357:13)
    at eval (index.js:1:21)
    at ./index.js (index_js.bootstrap.js:28:1)
    at __webpack_require__ (bootstrap.js:284:33)
    at Function.fn (bootstrap.js:592:21)
```

(`on_assembly_change` is the Rust function being called, which sort of has bindings generated, as you can see)

**Comment by FlareFlo** [comment]
> I have this exact issue, as soon as I upgrade to web_sys 0.3.61 from 0.3.60 any call to a Rust function from JavaScript results in an undefined error like:
> 
> ```
> bootstrap.js:2 Error importing `index.js`: TypeError: Cannot read properties of undefined (reading 'on_assembly_change')
>     at Module.on_assembly_change (spcasm_web_bg.js:269:10)
>     at eval (index.js:36:46)
>     at __webpack_require__.a (bootstrap.js:357:13)
>     at eval (index.js:1:21)
>     at ./index.js (index_js.bootstrap.js:28:1)
>     at __webpack_require__ (bootstrap.js:284:33)
>     at Function.fn (bootstrap.js:592:21)
> ```
> 
> (`on_assembly_change` is the Rust function being called, which sort of has bindings generated, as you can see)

I get issues with my own functions, or some stack pointer calls, such as `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')`

**Comment by cryptoquick** [comment]
> That repo isn't demonstrating the original issue that you had in #3306, it's a completely separate issue which is occurring because you're not running `await init()` before using the wasm exports on `--target web`, as people already pointed out in #3306.
> 
> The *original* problem was with `--target bundler`, not `--target web`, and *that's* the issue that I believe is the same as this one and wasn't present in 0.2.83.

I actually updated the comment you responded to only a few minutes after I posted it. Please take another look.

**Comment by Liamolucko** [comment]
This is now fixed in `wasm-pack` v0.11.0.
