### ISSUE TITLE
js_globals::Date::to_locale_date_string test failing locally

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/wasm-bindgen#368]
Even with the latest node 10

```
$ nvm use 10
Now using node v10.5.0 (npm v6.1.0)
```

it fails locally for me:

```
failures:

---- js_globals::Date::to_locale_date_string stdout ----
···················································
running "cargo" "build" "--target" "wasm32-unknown-unknown"
exit: exit code: 0
dur: 0.601ms
stderr ---
   Compiling test28 v0.0.1 (file:///Users/fitzgen/src/wasm-bindgen/target/generated-tests/test28)
    Finished dev [unoptimized + debuginfo] target(s) in 0.55s

···················································
running "npm" "run" "run-webpack"
exit: exit code: 0
dur: 5.041ms
stdout ---

> @ run-webpack /Users/fitzgen/src/wasm-bindgen/target/generated-tests/test28
> webpack

Hash: 0025335020a4964bfc1e
Version: webpack 4.11.1
Time: 3668ms
Built at: 07/02/2018 1:11:20 PM
                           Asset          Size  Chunks             Chunk Names
                       bundle.js      9.64 KiB    main  [emitted]  main
                     0.bundle.js        68 KiB       0  [emitted]  
a7af4adcd48892d78296.module.wasm  unknown size       0  [emitted]  
                     1.bundle.js     747 bytes       1  [emitted]  
                   bundle.js.map      8.98 KiB    main  [emitted]  main
                 0.bundle.js.map      43.8 KiB       0  [emitted]  
                 1.bundle.js.map     656 bytes       1  [emitted]  
[./out.js] 37.7 KiB {0} [built]
[./out_bg.wasm] 235 KiB {0} [built]
[./run.js] 610 bytes {main} [built]
[./test.ts] 425 bytes {1} [built]
[assert] external "assert" 42 bytes {main} [built]
[process] external "process" 42 bytes {main} [built]
[util] external "util" 42 bytes {main} [built]

···················································
running "node" "/Users/fitzgen/src/wasm-bindgen/target/generated-tests/test28/bundle.js"
exit: exit code: 1
dur: 0.296ms
stderr ---
{ AssertionError [ERR_ASSERTION]: 'Wednesday, December 19, 2012' == 'Thursday, December 20, 2012'
    at Object.test (/Users/fitzgen/src/wasm-bindgen/target/generated-tests/test28/1.bundle.js:19:12)
    at ./run.js.Promise.all.then.results (/Users/fitzgen/src/wasm-bindgen/target/generated-tests/test28/bundle.js:212:22)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: 'Wednesday, December 19, 2012',
  expected: 'Thursday, December 20, 2012',
  operator: '==' }

thread 'js_globals::Date::to_locale_date_string' panicked at 'assertion failed: output.status.success()', tests/all/main.rs:521:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    js_globals::Date::to_locale_date_string

test result: FAILED. 142 passed; 1 failed; 0 ignored; 0 measured; 84 filtered out

error: test failed, to rerun pass '--test all'
```

I saw some comments go by my email about icu not being built unless a build flag was passed or some such, and that seems related.

Perhaps we should loosen the locale-related tests to just assert that a string is returned or something? It seems like multiple folks are running into this issue.

**Comment by jonathan-s** [comment]
I'll take a stab at this and see if I can make both travis and local machine agree with each other.

**Comment by ohanar** [comment]
I get failures for `to_locale_date_string` and `to_locale_string` locally. The only locale for which my local machine has agreed with travis is `en-US`.
