### ISSUE TITLE
__webpack_require__("../pkg sync recursive"  -> Error: Cannot find module 'crypto'

### ISSUE THREAD

**Issue by aep** [rustwasm/wasm-bindgen#778]
i'm not sure how webpack actually works so sorry if this is obvious somehow.

```
Error importing `index.js`: Error: Cannot find module 'crypto'
    at webpackEmptyContext (webpack:///../pkg_sync?:2:10)
    at Module.__wbg_require_443fbcad222426b2 (webpack:///../pkg/carrier_web.js?:211:70)
    at __wbg_require_443fbcad222426b2 (http://localhost:8080/bootstrap.js:95:106)
    at _$LT$rand..rngs..os..imp..OsRng$u20$as$u20$rand..rngs..os..OsRngImpl$GT$::new::h86c537fc9bdcb29e (wasm-function[37]:138)
    at rand::rngs::os::OsRng::new::hbf5cc1d8c4352b91 (wasm-function[34]:17)
    at carrier_core::identity::Secret::gen::h07297757f0e8017b (wasm-function[31]:55)
    at stuff (wasm-function[25]:97)
    at Module.stuff (webpack:///../pkg/carrier_web.js?:161:65)
    at eval (webpack:///./index.js?:6:50)
    at Module../index.js (http://localhost:8080/0.bootstrap.js:45:1)
```

in carrier_web.js: 

```js
function __wbg_require_443fbcad222426b2(arg0, arg1) {
    let varg0 = getStringFromWasm(arg0, arg1);
    return addHeapObject(__webpack_require__("../pkg sync recursive")(varg0));
}

```
this doesnt look correct to me. can require really contain spaces?

where is this generated?

**Comment by aep** [comment]
turns out its coming from here: https://github.com/rust-random/rand/blob/d162a5ef3ca7dd3cdcbc02d800dd8b1acef0847b/src/rngs/os.rs#L1133

apparantly their check doesnt work

**Comment by aep** [comment]
looks like unrelated issues. the warning about the __webpack_require__ is still here.

WARNING in ../pkg/carrier_web.js 225:25-39
Critical dependency: the request of a dependency is an expression

```
223 export function __wbg_require_443fbcad222426b2(arg0, arg1) {
224     let varg0 = getStringFromWasm(arg0, arg1);
225     return addHeapObject(require(varg0));
226 }
```

**Comment by alexcrichton** [comment]
I believe this is an issue with the `rand` crate, so closing in favor of the rand crate itself
